import { type NextPage } from "next";
import { useState } from "react";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";
import { Header } from "~/components/Header";

import { api, type RouterOutputs } from "~/utils/api";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({
    text: "world",
  });

  return (
    <>
      <Head>
        <title>Note Taker</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Content />
     
    </>
  );
};

export default Home;

const Content: React.FC = () => {
  const { data: sessionData } = useSession()

  const [selectedTopic, setSelectedTopic] = useState<Topic | null>(null)

  const { data: topics, refetch: refetchTopics } = api.topic.getAll.useQuery(
    undefined,
    {
      enabled: sessionData?.user !== undefined,
      onSuccess: (data) => {
        setSelectedTopic(selectedTopic ?? data[0] ?? null)
      }
    }
  )

  const createTopic = api.topic.create.useMutation({
    onSuccess: () => {
      void refetchTopics()
    }
  });

  return (
    <div className="mx-5 mt-5 grid grid-cols-4 gap-2">
      <div className="px-2">
        <ul className="menu rounded-box w-56 bg-base-100 p-2">
          {topics?.map((topic) => (
            <li key={topic.id}>
              <a href="#"
              onClick={(evt)=> {
                evt.preventDefault()
              }}>
                {topic.title}
              </a>
            </li>
          ))}
        </ul>
        <input type={'text'} placeholder="New Topic" className="input-bordered input input-sm w-100"
        onKeyDown={(e)=> {
          if(e.key === "Enter"){
            createTopic.mutate({
              title: e.currentTarget.value
            });
            e.currentTarget.value="";
          }
        }} />
      </div>
    </div>
  )
};